marathon:
  distance: 6.76
  github-token: 
  github-json-path: https://api.github.com/repos/JamesHopbourn/sspai-series-article/contents/
  
mysql:
  host: 127.0.0.1
  port: 3306
  data-table: data
  team-table: team
  database: demo
  username: root
  password: newpassword

spring:
  main.web-application-type: NONE
  datasource:
    username: ${mysql.username}
    password: ${mysql.password}
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://${mysql.host}:${mysql.port}/${mysql.database}?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&allowMultiQueries=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/**/*.xml
  
---

spring:
  profiles: test
  jpa.hibernate.ddl-auto: none