spring:
  datasource:
    username: root
    password: newpassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:4406/demo?serverTimezone=Asia/Shanghai&useSSL=false&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true

mybatis:
  configuration-properties:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.testm.entity

marathon:
  distance: 6.76